#!/usr/bin/python
#coding:utf8
import sys, time
n = 101
for progress in range(1,n):
    time.sleep(0.05)
    speed = '='*(progress/2) +'-'*(progress%2) + ' '*((100-progress)/2)
    sys.stdout.write('[%s]\r'%speed)   #\r表示回车，在以前表示光标回到首部，而\n表示光标回到下一行行首
    sys.stdout.flush()
sys.stdout.write('\n')
sys.stdout.flush()


#### python已经有成熟的progress模块可以使用。
